"""empty message

Revision ID: 0a29ae797419
Revises: a204884fbd5f
Create Date: 2017-06-30 12:07:05.532650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a29ae797419'
down_revision = 'a204884fbd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Page_systems', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Page_systems', 'thumbnail')
    # ### end Alembic commands ###
