"""empty message

Revision ID: a204884fbd5f
Revises: b765ac96d35e
Create Date: 2017-06-30 11:34:59.500520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a204884fbd5f'
down_revision = 'b765ac96d35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navcats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Navcats')
    op.drop_constraint(u'page_systems_ibfk_2', 'Page_systems', type_='foreignkey')
    op.create_foreign_key(None, 'Page_systems', 'navcats', ['navcat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Page_systems', type_='foreignkey')
    op.create_foreign_key(u'page_systems_ibfk_2', 'Page_systems', 'Navcats', ['navcat_id'], ['id'])
    op.create_table('Navcats',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('navcats')
    # ### end Alembic commands ###
