"""empty message

Revision ID: b765ac96d35e
Revises: 
Create Date: 2017-06-30 11:14:52.193275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b765ac96d35e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Navcats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'Page_systems', sa.Column('navcat_id', sa.Integer(), nullable=True))
    op.add_column(u'Page_systems', sa.Column('url', sa.Text(), nullable=True))
    op.add_column(u'Page_systems', sa.Column('view', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Page_systems', 'Navcats', ['navcat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Page_systems', type_='foreignkey')
    op.drop_column(u'Page_systems', 'view')
    op.drop_column(u'Page_systems', 'url')
    op.drop_column(u'Page_systems', 'navcat_id')
    op.drop_table('Navcats')
    # ### end Alembic commands ###
